package com.example.foodtracker.model;

import java.io.Serializable;
import java.util.Map;

/**
 * Objects that extend the {@link Document} interface are able to be
 * represented as {@link com.google.firebase.firestore.FirebaseFirestore} instances
 */
public abstract class Document implements Serializable {

    private String firestoreId;

    /**
     * The name of the collection that stores objects of this type
     */
    public abstract String getCollectionName();

    /**
     * The key for the objects in the collection
     */
    public String getKey() {
        return firestoreId;
    }

    /**
     * Set the key for an object in this collection
     * Used when the key is auto-generated by Firestore to populate this field after creation
     */
    public void setKey(String key) {
        this.firestoreId = key;
    }

    /**
     * The data in this object that will be saved in the collection
     */
    public abstract Map<String, Object> getData();

    public boolean hasNonDefaultKey() { return false; }
}
