# Generated by Django 4.1.5 on 2023-01-03 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='jobApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=200)),
                ('jobTitle', models.CharField(max_length=200)),
                ('interviewPrep', models.TextField(blank=True, null=True)),
                ('appProgress', models.CharField(choices=[('submitted', 'Application Submitted'), ('interview', 'Interviewing'), ('noRes', 'No Response'), ('reject', 'Rejected'), ('offer', 'Offer Given'), ('accepted', 'Offer Accepted'), ('offerDec', 'Offer Declined')], default='submitted', max_length=21)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['companyName'],
            },
        ),
    ]
