# Generated by Django 4.1.5 on 2023-04-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='companyName',
            field=models.CharField(max_length=25),
        ),
    ]
